used_from_lib:
  time:
    connectors:
      - cmdb_graph.py
    objects:
      - time.py
  popgrowth:
    connectors:
      - cmdb_graph.py
    objects:
      - time.py 
    configurations:
      - species.yaml